// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWRTh3AGXO5Fki5_-uLKXzRPtwkQPZIrI',
    appId: '1:65267098306:web:05c1008dbb96d04747d15b',
    messagingSenderId: '65267098306',
    projectId: 'matagpila-1182c',
    authDomain: 'matagpila-1182c.firebaseapp.com',
    storageBucket: 'matagpila-1182c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrAX-3t2gKTid4a740tG_qGxkvBS8uu8',
    appId: '1:65267098306:android:1460a3b4bdbd6cf447d15b',
    messagingSenderId: '65267098306',
    projectId: 'matagpila-1182c',
    storageBucket: 'matagpila-1182c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA72AJsnUoyH1slfgpK9dxh2bWXqn9u3S8',
    appId: '1:65267098306:ios:8fb557f7693548bb47d15b',
    messagingSenderId: '65267098306',
    projectId: 'matagpila-1182c',
    storageBucket: 'matagpila-1182c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA72AJsnUoyH1slfgpK9dxh2bWXqn9u3S8',
    appId: '1:65267098306:ios:8fb557f7693548bb47d15b',
    messagingSenderId: '65267098306',
    projectId: 'matagpila-1182c',
    storageBucket: 'matagpila-1182c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWRTh3AGXO5Fki5_-uLKXzRPtwkQPZIrI',
    appId: '1:65267098306:web:9c44432929f8577847d15b',
    messagingSenderId: '65267098306',
    projectId: 'matagpila-1182c',
    authDomain: 'matagpila-1182c.firebaseapp.com',
    storageBucket: 'matagpila-1182c.firebasestorage.app',
  );

}